Bakery.Web/ViewModels/ShopViewModels.cs
using Bakery.Entities;
using Bakery.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bakery.Web.ViewModels
{
    public class CheckoutViewModel
    {
        public List<Product> CartProducts { get; set; }

        public List<int> CartProductIDs { get; set; }

        public ApplicationUser User { get; set; }
    }

    public class ShopViewModel
    {
        public int MaximumPrice { get; set; }
        public List<Category> FeaturedCategories { get; set; }
        public List<Product> Products { get; set; }
        public int? SortBy { get; set; }
        public int? CategoryID { get; set; }

        public Pager Pager { get; set; }
        public string SearchTerm { get; set; }
    }


    public class FilterProductsViewModel
    {
        public List<Product> Products { get; set; }

        public Pager Pager { get; set; }
        public int? SortBy { get; set; }
        public int? CategoryID { get; set; }
        public string SearchTerm { get; set; }
    }
}

Bakery.Web/Controllers/ShopController.cs
using Bakery.Entities;
using Bakery.Services;
using Bakery.Web.Code;
using Bakery.Web.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Bakery.Web.Controllers
{
    public class ShopController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryID, int? sortBy, int? pageNo)
        {
            var pageSize = ConfigurationsService.Instance.ShopPageSize();

            ShopViewModel model = new ShopViewModel();

            model.SearchTerm = searchTerm;
            model.FeaturedCategories = CategoriesService.Instance.GetFeaturedCategories();
            model.MaximumPrice = ProductsService.Instance.GetMaximumPrice();

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.SortBy = sortBy;
            model.CategoryID = categoryID;

            int totalCount = ProductsService.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);
            model.Products = ProductsService.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy, pageNo.Value, pageSize);

            model.Pager = new Pager(totalCount, pageNo, pageSize);

            return View(model);
        }

        public ActionResult FilterProducts(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryID, int? sortBy, int? pageNo)
        {
            var pageSize = ConfigurationsService.Instance.ShopPageSize();

            FilterProductsViewModel model = new FilterProductsViewModel();

            model.SearchTerm = searchTerm;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.SortBy = sortBy;
            model.CategoryID = categoryID;

            int totalCount = ProductsService.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);
            model.Products = ProductsService.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy, pageNo.Value, pageSize);

            model.Pager = new Pager(totalCount, pageNo, pageSize);

            return PartialView(model);
        }

        [Authorize]
        public ActionResult Checkout()
        {
            CheckoutViewModel model = new CheckoutViewModel();

            var CartProductsCookie = Request.Cookies["CartProducts"];

            if (CartProductsCookie != null && !string.IsNullOrEmpty(CartProductsCookie.Value))
            {
                model.CartProductIDs = CartProductsCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();

                model.CartProducts = ProductsService.Instance.GetProducts(model.CartProductIDs);

                model.User = UserManager.FindById(User.Identity.GetUserId());
            }

            return View(model);
        }

        //productIDs should beformatted like = "7-7-9-1"
        public JsonResult PlaceOrder(string productIDs)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            if (!string.IsNullOrEmpty(productIDs))
            {
                var productQuantities = productIDs.Split('-').Select(x => int.Parse(x)).ToList();

                var boughtProducts = ProductsService.Instance.GetProducts(productQuantities.Distinct().ToList());

                Order newOrder = new Order();
                newOrder.UserID = User.Identity.GetUserId();
                newOrder.OrderedAt = DateTime.Now;
                newOrder.Status = "Pending";
                newOrder.TotalAmount = boughtProducts.Sum(x => x.Price * productQuantities.Where(productID => productID == x.ID).Count());

                newOrder.OrderItems = new List<OrderItem>();
                newOrder.OrderItems.AddRange(boughtProducts.Select(x => new OrderItem() { ProductID = x.ID, Quantity = productQuantities.Where(productID => productID == x.ID).Count() }));

                var rowsEffected = ShopService.Instance.SaveOrder(newOrder);

                result.Data = new { Success = true, Rows = rowsEffected };
            }
            else
            {
                result.Data = new { Success = false };
            }

            return result;
        }
    }
}

Bakery.Web/Views/Shop/Checkout.cshtml
﻿
@model CheckoutViewModel

@if (Model != null && Model.CartProducts != null && Model.CartProducts.Count > 0)
{
    var i = 1;
    <section class="flat-row main-shop shop-slidebar">
        <div class="container">
            <div class="row">
                <div class="col-md-4 order-md-2 mb-4">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
                    </h4>
                    <ul class="list-group mb-3">
                        @foreach (var product in Model.CartProducts)
                        {
                            var productQuantity = Model.CartProductIDs.Where(productID => productID == product.ID).Count();

                            <li class="list-group-item d-flex justify-content-between lh-condensed" data-id="@product.ID">
                                <div>
                                    <h6 class="my-0">@i - @product.Name - Qty: @productQuantity</h6>
                                    <small class="text-muted">@(product.Description.Length > 100 ? product.Description.Substring(0, 99) : product.Description)</small>
                                </div>
                                <span class="text-muted">Unit Price: $ @product.Price - Total Price: @(productQuantity * product.Price)</span>
                            </li>

                            i++;
                        }

                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>$ @Model.CartProducts.Sum(x => x.Price * Model.CartProductIDs.Where(productID => productID == x.ID).Count())</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-8 order-md-1">
                    <form class="needs-validation" novalidate="">
                        <div class="row">
                            <div class="col-md-12 mb-3">
                                <label for="firstName">Name</label>
                                <input type="text" class="form-control" id="Name" placeholder="" value="@Model.User.Name" required="">
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="email">Email <span class="text-muted">(Optional)</span></label>
                            <input type="email" class="form-control" id="Email" placeholder="you@example.com" value="@Model.User.Email">
                        </div>

                        <div class="mb-3">
                            <label for="address">Address</label>
                            <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="" value="@Model.User.Address">
                        </div>

                        <hr class="mb-4">
                        <button id="placeOrderBtn" class="btn btn-primary btn-lg btn-block" type="button">Place Order!</button>
                    </form>
                </div>
            </div>
        </div><!-- /.container -->
    </section>


    <script>
	$("#placeOrderBtn").click(function () {
		$.ajax({
			url: '@Url.Action("PlaceOrder", "Shop")',
			data: {
				productIDs: '@string.Join("-", Model.CartProductIDs)'
			}
		})
        .done(function (response) {
        	if(response.Success)
        	{
        		$.cookie('CartProducts', '', { path: '/' });
        		updateCartProducts();

        		swal("Done", "Your Order has been placed.", "success").then((value) => {
        			window.location = '@Url.Action("Index", "Shop")';
        		});;
        	}
        	else{
        		swal("Failed", "Unable to place order.", "warning");
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});
    </script>
}
else
{
    <div>
        <b>No Products in Cart.</b>
    </div>
}

Bakery.Web/Views/Shop/FilterProducts.cshtml
@model FilterProductsViewModel

@{

    var defaultImageURL = "/Content/images/placeholder-image.png";
}

<div class="filter-shop clearfix">
    <p class="showing-product float-right">
        Showing @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize) + 1 ) – @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize) + (Model.Products.Count < Model.Pager.PageSize ? Model.Products.Count : Model.Pager.PageSize)) of @Model.Pager.TotalItems Products
    </p>
</div><!-- /.filte-shop -->
<div class="product-content product-threecolumn product-slidebar clearfix">
    <ul class="product style2 sd1">

        @foreach (var product in Model.Products)
        {
            var imageURL = string.IsNullOrEmpty(product.ImageURL) ? defaultImageURL : product.ImageURL;

            <li class="product-item">
                <div class="product-thumb clearfix">
                    <a href="#">
                        <img src="@imageURL" alt="image" style="height: 295px;">
                    </a>
                </div>
                <div class="product-info clearfix">
                    <span class="product-title">
                        @product.Name
                    </span>
                    <div class="price">
                        <ins>
                            <span class="amount">$ @product.Price</span>
                        </ins>
                    </div>
                </div>
                <div class="add-to-cart text-center">
                    <a class="productAddToCart" data-id="@product.ID">ADD TO MY ORDER</a>
                </div>
                <a href="#" class="like"><i class="fa fa-heart-o"></i></a>
            </li>
        }
    </ul><!-- /.product -->
</div><!-- /.product-content -->

@if (Model.Pager != null && Model.Pager.TotalPages > 1)
{
    <div class="product-pagination text-center clearfix">
        <ul class="flat-pagination">
            @if (Model.Pager.CurrentPage > 1)
            {
                <li class="prev">
                    <a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = Model.Pager.CurrentPage - 1, sortBy = Model.SortBy, categoryID = Model.CategoryID })" class="pageDataLink"><i class="fa fa-angle-left"></i></a>
                </li>
            }

            @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <li class="@activeClass"><a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = page, sortBy = Model.SortBy, categoryID = Model.CategoryID })" title="" class="pageDataLink">@page</a></li>
            }

            @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <li><a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = Model.Pager.CurrentPage + 1, sortBy = Model.SortBy, categoryID = Model.CategoryID})" class="pageDataLink"><i class="fa fa-angle-right"></i></a></li>
            }
        </ul><!-- /.flat-pagination -->
    </div>
}

<input type="hidden" id="SearchTerm" value="@Model.SearchTerm" />
<input type="hidden" id="SortBy" value="@Model.SortBy" />
<input type="hidden" id="CategoryID" value="@Model.CategoryID" />

<script>
    $(".pageDataLink").click(function () {
        var url = $(this).attr("data-href");

        if (url != "" || url != undefined) {
            GetData(url);
        }
    });

    var products;
    $(".productAddToCart").click(function () {
        var existingCookieData = $.cookie('CartProducts');

        if (existingCookieData != undefined && existingCookieData != "" && existingCookieData != null) {
            products = existingCookieData.split('-');
        }
        else {
            products = [];
        }

        var productID = $(this).attr('data-id');

        products.push(productID);

        $.cookie('CartProducts', products.join('-'), { path: '/' });

        updateCartProducts();

        swal("Done", "Product Added to Cart!", "success");
    });

</script>

Bakery.Web/Views/Shop/Index.cshtml
@using Bakery.Web.Code

@model ShopViewModel

@{
    ViewBag.Title = "Index";

}

<!-- Page title -->
<div class="page-title parallax parallax1">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="page-title-heading">
					<h1 class="title">Shop</h1>
				</div><!-- /.page-title-heading -->
			</div><!-- /.col-md-12 -->
		</div><!-- /.row -->
	</div><!-- /.container -->
</div><!-- /.page-title -->

<section class="flat-row main-shop shop-slidebar">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="sidebar slidebar-shop">
					<div class="widget widget-search">
						<form role="search" method="get" class="search-form" action="@Url.Action("Index", "Shop")">
							<label>
								<input type="search" class="search-field" placeholder="Search …" value="@Model.SearchTerm" name="searchTerm">
							</label>
							<input type="submit" class="search-submit" value="Search">
						</form>
					</div><!-- /.widget-search -->
					<div class="widget widget-sort-by">
						<h5 class="widget-title">
							Sort By
						</h5>
						<ul>
							<li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEnums.Default, categoryID = Model.CategoryID })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnums.Default ? "active" : string.Empty : string.Empty)">Default - Newest</a></li>
							<li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEnums.Popularity, categoryID = Model.CategoryID  })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnums.Popularity ? "active" : string.Empty : string.Empty)">Popularity</a></li>
							<li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEnums.PriceLowToHigh, categoryID = Model.CategoryID  })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnums.PriceLowToHigh ? "active" : string.Empty : string.Empty)">Price: low to high</a></li>
							<li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEnums.PriceHighToLow, categoryID = Model.CategoryID  })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnums.PriceHighToLow ? "active" : string.Empty : string.Empty)">Price: high to low</a></li>
						</ul>
					</div>
					<div class="widget widget_tag">
						<h5 class="widget-title">
							Featured Categories
						</h5>
						<div class="tag-list">
							@foreach (var category in Model.FeaturedCategories)
							{
								<a data-href="@Url.Action("FilterProducts", "Shop", new { categoryID = category.ID, sortBy = Model.SortBy })" class="dataLink @(Model.CategoryID.HasValue && Model.CategoryID.Value == category.ID ? "active" : string.Empty)">@category.Name</a>
							}
						</div>
					</div>
					<div class="widget widget-price">
						<h5 class="widget-title">Filter by price</h5>
						<div class="price-filter">
							<div id="slide-range"></div>
							<p class="amount">
								Price: <input type="text" id="amount" disabled="">
							</p>
						</div>
					</div><!-- /.widget -->
					<a href="@Url.Action("Index", "Shop")" class="btn btn-danger">Reset Filters</a>
				</div><!-- /.sidebar -->
			</div><!-- /.col-md-3 -->
			<div class="col-md-9">
				<div id="productsDiv">
					@{
						var filterProductsViewModel = new FilterProductsViewModel();
						filterProductsViewModel.Products = Model.Products;
						filterProductsViewModel.Pager = Model.Pager;
						filterProductsViewModel.CategoryID = Model.CategoryID;
						filterProductsViewModel.SortBy = Model.SortBy;

						Html.RenderPartial("FilterProducts", filterProductsViewModel);
					}
				</div>

			</div><!-- /.col-md-9 -->
		</div><!-- /.row -->
	</div><!-- /.container -->
</section><!-- /.flat-row -->

<script>

	var callTimeout;
	var priceSlider = $("#slide-range").slider({
		range: true,
		min: 0,
		max: @Model.MaximumPrice,
		values: [0, @Model.MaximumPrice],
		slide: function (event, ui) {
			var minPrice = ui.values[0];
			var maxPrice = ui.values[1];

			$("#amount").val("$" + minPrice + ".00" + " - " + "$" + maxPrice + ".00");

			clearTimeout(callTimeout);
			callTimeout = setTimeout(PriceRangeChange, 500);
		}
	});

	$(".dataLink").click(function () {
		var url = $(this).attr("data-href");

		if (url != "" || url != undefined) {
			GetData(url);
		}
	});

	function GetData(dUrl){
		console.log("getdata in");
		showLoader();

		$.ajax({
			url: dUrl,
			data: {
				minimumPrice : priceSlider.slider("values", 0),
				maximumPrice : priceSlider.slider("values", 1)
			}
		})
        .done(function (response) {
        	console.log("done");
        	$("#productsDiv").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	console.log("fail");
        	alert("FAIL");
        })
		.always(function(){
			console.log("always");
			hideLoader();
		});
		console.log("getdata out");
	}

	function PriceRangeChange(){
		$.ajax({
			url: '@Url.Action("FilterProducts", "Shop")',
			data: {
				searchTerm: $("#SearchTerm").val(),
				sortBy: $("#SortBy").val(),
				categoryID: $("#CategoryID").val(),
				minimumPrice : priceSlider.slider("values", 0),
				maximumPrice : priceSlider.slider("values", 1)
			}
		})
        .done(function (response) {
        	$("#productsDiv").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	}
</script>