Bakery.Web/ViewModels/ProductViewModels.cs
using Bakery.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bakery.Web.ViewModels
{
    public class ProductSearchViewModel
    {
        public List<Product> Products { get; set; }
        public string SearchTerm { get; set; }

        public Pager Pager { get; set; }
    }

    public class NewProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }

    public class EditProductViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }

    public class ProductViewModel
    {
        public Product Product { get; set; }
    }
}

Bakery.Web/Controllers/ProductController.cs
using Bakery.Entities;
using Bakery.Services;
using Bakery.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bakery.Web.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search, int? pageNo)
        {
            var pageSize = ConfigurationsService.Instance.PageSize();

            ProductSearchViewModel model = new ProductSearchViewModel();
            model.SearchTerm = search;

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var totalRecords = ProductsService.Instance.GetProductsCount(search);
            model.Products = ProductsService.Instance.GetProducts(search, pageNo.Value, pageSize);

            model.Pager = new Pager(totalRecords, pageNo, pageSize);

            return PartialView(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();

            model.AvailableCategories = CategoriesService.Instance.GetAllCategories();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
            var newProduct = new Product();
            newProduct.Name = model.Name;
            newProduct.Description = model.Description;
            newProduct.Price = model.Price;
            newProduct.Category = CategoriesService.Instance.GetCategory(model.CategoryID);
            newProduct.ImageURL = model.ImageURL;

            ProductsService.Instance.SaveProduct(newProduct);
            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();

            var product = ProductsService.Instance.GetProduct(ID);

            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageURL = product.ImageURL;

            model.AvailableCategories = CategoriesService.Instance.GetAllCategories();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var existingProduct = ProductsService.Instance.GetProduct(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.Price = model.Price;

            existingProduct.Category = null; //mark it null. Because the referncy key is changed below
            existingProduct.CategoryID = model.CategoryID;

            //dont update imageURL if its empty
            if (!string.IsNullOrEmpty(model.ImageURL))
            {
                existingProduct.ImageURL = model.ImageURL;
            }

            ProductsService.Instance.UpdateProduct(existingProduct);

            return RedirectToAction("ProductTable");
        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductsService.Instance.DeleteProduct(ID);

            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Details(int ID)
        {
            ProductViewModel model = new ProductViewModel();

            model.Product = ProductsService.Instance.GetProduct(ID);

            if (model.Product == null) return HttpNotFound();

            return View(model);
        }
    }
}

Bakery.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bakery.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };

                //var newImage = new Image() { Name = fileName };

                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

Bakery.Web/Controllers/WidgetsController.cs
using Bakery.Services;
using Bakery.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bakery.Web.Controllers
{
    public class WidgetsController : Controller
    {
        // GET: Widgets
        public ActionResult Products(bool isLatestProducts, int? CategoryID = 0)
        {
            ProductsWidgetViewModel model = new ProductsWidgetViewModel();
            model.IsLatestProducts = isLatestProducts;

            if (isLatestProducts)
            {
                model.Products = ProductsService.Instance.GetLatestProducts(4);
            }
            else if (CategoryID.HasValue && CategoryID.Value > 0)
            {
                model.Products = ProductsService.Instance.GetProductsByCategory(CategoryID.Value, 4);
            }
            else
            {
                model.Products = ProductsService.Instance.GetProducts(1, 8);
            }

            return PartialView(model);
        }
    }
}

Bakery.Web/Views/Product/Create.cshtml
﻿
@model NewProductViewModel

@{
    ViewBag.Title = "Create";

    var imageURL = "/Content/images/placeholder-image.png";
}

<h2>Create Product</h2>

<form id="createProduct">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        <option value="@category.ID">@category.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" />
            </div>
            <div class="form-group">
                <label>Price</label>
                <input class="form-control" name="Price" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
            <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />
            </div>
        </div>
    </div>
</form>

<script>
	$('#createProduct').validate({
		rules: {
			Name: {
				required: true,
				minlength: 5,
				maxlength: 50,
			},
			Description: {
				maxlength: 500
			},
			Price: {
				range: [1, 100000]
			}
		},
		messages: {
			Name: {
				required: 'Name is required',
				minlength: 'Minimum Length is 5',
				maxlength: 'Maximum Length is 50'
			},
			Description: {
				maxlength: 'Maximum Length is 500'
			},
			Price: {
				range: 'Price must be within range of 1 - 100000.'
			}
		}
	});

	$("#imageUpload").change(function () {
		var element = this;

		var formData = new FormData();

		var totalFiles = element.files.length;

		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}

		$.ajax({
			type: 'POST',
			url: '@Url.Action("UploadImage", "Shared")',
			dataType: 'json',
			data: formData,
			contentType: false,
			processData: false
		})
        .done(function (response) {
        	console.log(response);

        	if (response.Success) {
        		$("#ImageURL").val(response.ImageURL);
        		$("#productImage").attr("src", response.ImageURL);
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});

	$("#saveBtn").click(function () {
		if ($("#createProduct").valid()) {
			$.ajax({
				type: 'POST',
				url: '@Url.Action("Create", "Product")',
				data: $("#createProduct").serialize()
			})
			.done(function (response) {
				$("#tableContainer").html(response);
				$("#actionContainer").html("");

				focusAction("tableContainer");
			})
			.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				alert("FAIL");
			});
		}
		else {
			swal({
				title: "Warning",
				text: "Please enter all valid data in fields.",
				icon: "warning",
				buttons: true,
				dangerMode: true,
			});
		}
	});

	$("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContainer");
	});
</script>

Bakery.Web/Views/Product/Details.cshtml
@model ProductViewModel

@if (Model != null && Model.Product != null)
{
    var defaultImageURL = "/Content/images/placeholder-image.png";

    var imageURL = string.IsNullOrEmpty(Model.Product.ImageURL) ? defaultImageURL : Model.Product.ImageURL;
    <!-- Page title -->
    <div class="page-title parallax parallax1">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-title-heading">
                        <h1 class="title">
                            @Model.Product.Name
                        </h1>
                    </div><!-- /.page-title-heading -->
                </div><!-- /.col-md-12 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.page-title -->

    <section class="flat-row main-shop shop-detail">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="wrap-flexslider">
                        <div class="inner">
                            <div class="flexslider style-1 has-relative">
                                <ul class="slides">
                                    <li data-thumb="@imageURL">
                                        <img src="@imageURL" alt="Image">
                                        <div class="flat-icon style-1">
                                            <a href="@imageURL" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                        </div>
                                    </li>
                                    @*<li data-thumb="images/shop/sh-detail/thumb-detail-02.jpg">
                                            <img src="images/shop/sh-detail/detail-01.jpg" alt="Image">
                                            <div class="flat-icon style-1">
                                                <a href="images/shop/sh-detail/detail-01.jpg" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                            </div>
                                        </li>
                                        <li data-thumb="images/shop/sh-detail/thumb-detail-03.jpg">
                                            <img src="images/shop/sh-detail/detail-01.jpg" alt="Image">
                                            <div class="flat-icon style-1">
                                                <a href="images/shop/sh-detail/detail-01.jpg" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                            </div>
                                        </li>
                                        <li data-thumb="images/shop/sh-detail/thumb-detail-04.jpg">
                                            <img src="images/shop/sh-detail/detail-01.jpg" alt="Image">
                                            <div class="flat-icon style-1">
                                                <a href="images/shop/sh-detail/detail-01.jpg" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                            </div>
                                        </li>*@
                                </ul>
                            </div><!-- /.flexslider -->
                        </div>
                    </div>
                </div><!-- /.col-md-6 -->

                <div class="col-md-6">
                    <div class="product-detail">
                        <div class="inner">
                            <div class="content-detail">
                                <h2 class="product-title">
                                    @Model.Product.Name
                                </h2>
                                <div class="flat-star style-1">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-half-o"></i>
                                    <i class="fa fa-star-half-o"></i>
                                    <span>(1)</span>
                                </div>
                                <p>
                                    @Model.Product.Description
                                </p>
                                <div class="price">
                                    <ins>
                                        <span class="amount">
                                            $ @Model.Product.Price
                                        </span>
                                    </ins>
                                </div>
                                <div class="product-quantity">
                                    <div class="quantity">
                                        <input type="text" value="1" name="quantity-number" class="quantity-number">
                                        <span class="inc quantity-button">+</span>
                                        <span class="dec quantity-button">-</span>
                                    </div>
                                    <div class="add-to-cart text-center">
                                        <a class="productAddToCart" data-id="@Model.Product.ID">ADD TO MY ORDER</a>
                                    </div>
                                    <div class="box-like">
                                        <a href="#" class="like"><i class="fa fa-heart-o"></i></a>
                                    </div>
                                </div>
                                <div class="product-categories">
                                    <span>Categories: </span><a href="#">@Model.Product.Category.Name</a>
                                </div>
                                <ul class="flat-socials">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>

                                </ul>
                            </div>
                        </div>
                    </div><!-- /.product-detail -->
                </div>
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section><!-- /.flat-row -->



    <section class="flat-row shop-related">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title-section margin-bottom-55">
                        <h2 class="title">Related Products</h2>
                    </div>

                    @{Html.RenderAction("Products", "Widgets", new { isLatestProducts = false, CategoryID = Model.Product.Category.ID });}

                </div>
            </div><!-- /.row -->
        </div>
    </section>

}


<script>
    var products;
    $(".productAddToCart").click(function () {
        var existingCookieData = $.cookie('CartProducts');

        if (existingCookieData != undefined && existingCookieData != "" && existingCookieData != null) {
            products = existingCookieData.split('-');
        }
        else {
            products = [];
        }

        var productID = $(this).attr('data-id');

        products.push(productID);

        $.cookie('CartProducts', products.join('-'), { path: '/' });

        updateCartProducts();

        swal("Done", "Product Added to Cart!", "success");
    });

</script>

Bakery.Web/Views/Product/Edit.cshtml
@model EditProductViewModel

@{
    ViewBag.Title = "Edit";

    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/placeholder-image.png";
}

<h2>Edit Product</h2>

<form id="editProduct">
    <input type="hidden" name="ID" value="@Model.ID" />
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                        <option value="@category.ID" @selected>@category.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label>Price</label>
                <input class="form-control" name="Price" value="@Model.Price" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>

            <button id="updateBtn" type="button" class="btn btn-primary">Update</button>
            <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />
            </div>
        </div>
    </div>

</form>

<script>
	$('#editProduct').validate({
		rules: {
			Name: {
				required: true,
				minlength: 5,
				maxlength: 50,
			},
			Description: {
				maxlength: 500
			},
			Price: {
				range: [1, 100000]
			}
		},
		messages: {
			Name: {
				required: 'Name is required',
				minlength: 'Minimum Length is 5',
				maxlength: 'Maximum Length is 50'
			},
			Description: {
				maxlength: 'Maximum Length is 500'
			},
			Price: {
				range: 'Price must be within range of 1 - 100000.'
			}
		}
	});

	$("#imageUpload").change(function () {
		var element = this;

		var formData = new FormData();

		var totalFiles = element.files.length;

		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}

		$.ajax({
			type: 'POST',
			url: '@Url.Action("UploadImage", "Shared")',
			dataType: 'json',
			data: formData,
			contentType: false,
			processData: false
		})
        .done(function (response) {
        	console.log(response);

        	if (response.Success) {
        		$("#ImageURL").val(response.ImageURL);
        		$("#productImage").attr("src", response.ImageURL);
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});

	$("#updateBtn").click(function () {
		if ($("#editProduct").valid()) {
			$.ajax({
				type: 'POST',
				url: '@Url.Action("Edit", "Product")',
				data: $("#editProduct").serialize()
			})
			.done(function (response) {
				$("#tableContainer").html(response);
				$("#actionContainer").html("");
				focusAction("tableContainer");
			})
			.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				alert("FAIL");
			});
		}
		else {
			swal({
				title: "Warning",
				text: "Please enter all valid data in fields.",
				icon: "warning",
				buttons: true,
				dangerMode: true,
			});
		}
	});

	$("#cancelBtn").click(function () {
		$("#actionContainer").html("");
		focusAction("tableContainer");
	});
</script>

Bakery.Web/Views/Product/Index.cshtml
 
@{
    ViewBag.Title = "Products";
}

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Products
                    </h2>
                </div>
            </div>
        </div>

        <div id="tableContainer">
            @{
                Html.RenderAction("ProductTable");
            }
        </div>

        <hr />
        <div id="actionContainer">

        </div>
    </div>
</section>


<script>
	function focusAction(controlToFocus) {
		$('html, body').animate({
			scrollTop: $("#" + controlToFocus).offset().top - 100
		}, 1000);
	}
</script>

Bakery.Web/Views/Product/ProductTable.cshtml
@model ProductSearchViewModel

@{
    ViewBag.Title = "ProductTable";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>


<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Search</label>
                    <input class="form-control" id="searchTxt" name="Search" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="searchBtn">Search</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="resetBtn">Reset</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="newBtn">New</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table id="ProductsTable" class="table table-striped">
        <thead>
            <tr>
                <th class="font-weight-bold">Product Name</th>
                <th class="font-weight-bold">Category</th>
                <th class="font-weight-bold">Price</th>
                <th class="font-weight-bold wrap-td">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null && Model.Products.Count > 0)
            {

                foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>
                            @if (product.Category != null)
                            {
                                <text>@product.Category.Name</text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@product.Price</td>
                        <td class="wrap-td">
                            <button class="editBtn" data-id="@product.ID">Edit</button>
                            <button class="deleteBtn" data-id="@product.ID">Delete</button>
                            <button class="addtoCart" data-id="@product.ID">ADD TO MY ORDER</button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td class="text-danger" colspan="4">No Products found.</td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        @if (Model.Pager != null && Model.Pager.TotalPages > 1)
        {

            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageno="1">First</button>
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</button>
            }

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <button class="@activeClass pageButtons" data-pageno="@page">@page</button>
            }

            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</button>
                <button class="pageButtons" data-pageno="@Model.Pager.EndPage">Last</button>
            }
        }
    </div>
</div>

<script>

	$(".pageButtons").click(function () {
		$.ajax({
			url: '@Url.Action("ProductTable", "Product")',
			data: {
				pageNo : $(this).attr("data-pageno")
			}
		})
        .done(function (response) {
        	$("#tableContainer").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});

	$("#searchBtn").click(function () {
		var searchValue = $("#searchTxt").val();

		$.ajax({
			url: '@Url.Action("ProductTable", "Product")',
			data: {
				search: searchValue
			}
		})
        .done(function (response) {
        	$("#tableContainer").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});

	$("#resetBtn").click(function () {
		var searchValue = '';

		$.ajax({
			url: '@Url.Action("ProductTable", "Product")',
			data: {
				search: searchValue
			}
		})
        .done(function (response) {
        	$("#tableContainer").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});

	$("#newBtn").click(function () {
		$.ajax({
			url: '@Url.Action("Create", "Product")',
		})
        .done(function (response) {
        	$("#actionContainer").html(response);

        	focusAction("actionContainer");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});

	$(".editBtn").click(function () {
		$.ajax({
			url: '@Url.Action("Edit", "Product")',
			data: {
				ID: $(this).attr('data-id')
			}
		})
        .done(function (response) {
        	$("#actionContainer").html(response);

        	focusAction("actionContainer");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});

	$(".deleteBtn").click(function () {

		swal({
			title: "Confirm?",
			text: "Are you sure you want to delete this product?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
			if (willDelete) {
				$.ajax({
					type: 'POST',
					url: '@Url.Action("Delete", "Product")',
					data: {
						ID: $(this).attr('data-id')
					}
				})
				.done(function (response) {
					$("#tableContainer").html(response);

					swal("Record deleted Successfully.", {
						icon: "success",
					});
				})
				.fail(function (XMLHttpRequest, textStatus, errorThrown) {
					alert("FAIL");
				});

			}
		});

		//var confirmDelete = confirm("Are you sure you want to delete this product?");

		//if (confirmDelete)
		//{
		//	$.ajax({
		//		type: 'POST',
		//		url: '/Product/Delete',
		//		data: {
		//			ID: $(this).attr('data-id')
		//		}
		//	})
		//	.done(function (response) {
		//		$("#tableContainer").html(response);
		//	})
		//	.fail(function (XMLHttpRequest, textStatus, errorThrown) {
		//		alert("FAIL");
		//	});
		//}
	});

	var products = [];
	$(".addtoCart").click(function () {
		var productID = $(this).attr('data-id');

		products.push(productID);

		$.cookie('CartProducts', products.join('-'), { path: '/' });

		alert("Product added to Cart.");
	});
</script>